# Generated by Django 3.0.2 on 2020-05-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('symbol', models.CharField(max_length=15)),
                ('period', models.CharField(choices=[('1m', '1 Minute'), ('5m', '5 Minute'), ('15m', '15 Minute'), ('30m', '30 Minute'), ('1h', 'Hourly'), ('1d', 'Daily'), ('1wk', 'Weekly'), ('1mo', 'Monthly'), ('1y', 'Yearly'), ('max', 'Maximum')], default='1mo', max_length=5)),
            ],
        ),
    ]
